import os
from groq import Groq
from dotenv import load_dotenv
from debug_logger import debug_log

load_dotenv()


class LLMClient:

    def __init__(self):
        self.provider = "groq"
        self.model = "llama-3.1-8b-instant"

        self.client = Groq(
            api_key=os.getenv("GROQ_API_KEY")
        )

# ============================================================
# 📌 HOW TOOL CALLS COME FROM LLM (REFERENCE STRUCTURE)
#
# When we send tools=tool_schemas to LLM, the model can return
# structured tool call requests instead of normal text reply.
#
# Example Raw API Response (Conceptual):
#
# {
#   "choices": [
#     {
#       "message": {
#         "role": "assistant",
#         "content": null,
#         "tool_calls": [
#           {
#             "id": "call_123",
#             "type": "function",
#             "function": {
#               "name": "calculate_sum",
#               "arguments": "{\"a\":45,\"b\":67}"
#             }
#           }
#         ]
#       }
#     }
#   ]
# }
#
# Meaning:
# - LLM is NOT replying to user yet
# - LLM is asking system to execute tool first
# - tool_calls is generated by LLM automatically
#
# Our Flow:
# 1️⃣ Detect message.tool_calls
# 2️⃣ Execute tool in Python
# 3️⃣ Add tool result back as role="tool"
# 4️⃣ Call LLM again → LLM gives final answer
#
# IMPORTANT:
# tool_calls comes from LLM response — not created by our code
# ============================================================


    def generate(self, messages, tools=None):

        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=messages,
                tools=tools,
                tool_choice="auto"
            )

            return response.choices[0].message

        except Exception as e:

            error_text = str(e)

            # ⭐ Catch tool misuse from model
            if "tool_use_failed" in error_text or "<function=" in error_text:

                print("[DEBUG] Model attempted invalid tool syntax. Retrying...")

                # Retry once forcing normal text first
                response = self.client.chat.completions.create(
                    model=self.model,
                    messages=messages
                )

                return response.choices[0].message

            # Re-raise if other error
            raise

